### PR TITLE
Increase racing bias upper limit to wait for remote cache a bit more

### PR DESCRIPTION
**Pull request by goodov**
We've observed that when most objects are available remotely, utilizing any local resources in racing mode may limit the performance of scandeps.

Currently, the `racing_bias` upper limit restricts higher values, preventing more remote objects from being fetched without triggering local actions. This change raises the upper delay limit for local actions beyond `download_latency_p90 * 2`.

### CODE REVIEW

**Comment by goodov** [comment]
@gkousik please take a look? Thank you!

**Comment by gkousik** [comment]
I think raising this limit is ok, but I do want to clarify the use case in the documentation. Could you modify the doc line to state something like "A value of 0 to 1 is recommended for most builds. In case of builds with slow include scanning times due to excessive local execution, a value of > 1 maybe used to improve the overall build time". 

Do you see faster overall build times when you set this to a value > 1? Scandeps is on the critical path to constructing and offloading a C++ action to RBE, but reproxy also limits local execution based on available local resources. If local resource limit is hit, we do queue up actions before starting to run them. But this queue is FIFO iirc which could mean we end up running an action locally instead of doing input processing and I can see that being suboptimal.

So I also wonder if we should have a priority queue for local execution with scandeps given a higher priority over other local execs, especially if they have a cache hit (not saying you should do this in this PR, but just thinking out loud).

**Comment by bentekkie** [comment]
I would also suggest tuning the cas concurrency flags as well (we should add more documentation). Those flags are defined in the SDK. They should be able to help speed up downloads of artifacts for cache hits. You can see some sample values in the chromium developer config https://source.chromium.org/chromium/chromium/src/+/main:buildtools/reclient_cfgs/reproxy_cfg_templates/reproxy.cfg.template;l=1?q=Reproxy.cfg.&sq=&ss=chromium

**Comment by gkousik** [comment]
Actually with `scandeps_server` (where include scanning happens in a separate process), local execution pool isn't shared with local execution and they both run in parallel (this would overbook the system resources and slowdown scandeps) - is this what you are seeing?

**Comment by goodov** [comment]
> Could you modify the doc line <...>

Sure. The doc line is updated.

> I would also suggest tuning the cas concurrency flags as well (we should add more documentation). Those flags are defined in the SDK. They should be able to help speed up downloads of artifacts for cache hits. You can see some sample values in the chromium developer config https://source.chromium.org/chromium/chromium/src/+/main:buildtools/reclient_cfgs/reproxy_cfg_templates/reproxy.cfg.template;l=1?q=Reproxy.cfg.&sq=&ss=chromium

We use this `reproxy.cfg.template` as the base for our setup, so we have all these values set. I can experiment with tuning those, thanks!

> Actually with `scandeps_server` (where include scanning happens in a separate process), local execution pool isn't shared with local execution and they both run in parallel (this would overbook the system resources and slowdown scandeps) - is this what you are seeing?

Yep, I believe this is the case. Any local load does slowdown scandeps. We currently use this config on linux nodes, but still see 80-100 local racing actions being run while the build is 100% cache-hittable:
```
RBE_local_resource_fraction=0.1
RBE_racing_bias=1
```

**Comment by goodov** [comment]
@bentekkie ptal

**Comment by goodov** [comment]
@gkousik ptal? Not sure what else can I do here.

**Review by gkousik — APPROVED** [review]

**Comment by gkousik** [comment]
Thanks for the followup, will import it today.

**Pull request closed without merging**
